version: 2

project_name: discli

before:
  hooks:
    - go mod tidy

builds:
  - id: discli
    main: ./cmd/discli
    binary: discli
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.ShortCommit}}
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md
      - LICENSE

brews:
  - name: discli
    folder: Formula
    repository:
      owner: patrickjm
      name: homebrew-tap
    homepage: https://github.com/patrickjm/discli
    description: Discord CLI + local daemon
    license: MIT

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: patrickjm
    name: discli
